### ISSUE TITLE
Unable to download RAF files

### ISSUE THREAD

**Issue by RampantPanda** [damonlynch/rapid-photo-downloader#102]
My camera saves jpeg files and raf files to separate sd cards. Jpeg files downloaded just fine, but with raf files RPD gets stuck when scanning the photos. "Download" button stays inactive.

I tried copying the files to my computer and importing from there, but the same result.

Log file attached.  

[rpd-bug-report-20230402.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/11131376/rpd-bug-report-20230402.tar.gz)

**Comment by damonlynch** [comment]
Sorry for the delayed response. I have been dealing with significant health problems. Are you willing to test an unreleased version of Rapid Photo Downloader that may (or may not) fix the problem you have encountered? I do not own a Fujifilm camera, so help from Fujifilm owners is vital if this bug is to be solved.

**Comment by RampantPanda** [comment]
Thanks for the reply. Sorry to hear about your problems, hope everything is OK now.

I can't test this problem anymore since I reinstalled my OS and now everything works fine. Maybe it wasn't a RPD problem. 

I also seem to have opened two issues (#101 ) on this, sorry about that.

But I'd love to help test an unreleased version with Fuji files if that helps the project.
