### ISSUE TITLE
Installation error: Failed to install application requirements

### ISSUE THREAD

**Issue by gverduci** [damonlynch/rapid-photo-downloader#106]
OS Ubuntu 23.04

steps to reproduce:
1. download the install.py file from the git repo (or from https://damonlynch.net/rapid/download.html)
2. run the command "python3 install.py".

the output of the command is:

/home/XXXXXXX/Downloads/install.py:3982: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
  lang = locale.getdefaultlocale()[0]
Detected Linux distribution Ubuntu 23.04 
Downloading https://launchpad.net/rapid/pyqt/0.9.34/+download/rapid-photo-downloader-0.9.34.tar.gz (8.51 MB)
Downloading.... done!

Determining most appropriate PyQt5 package...
...will use PyQt5 packaged by Ubuntu 23.04.

Querying package system to see if an older version of Rapid Photo Downloader is installed (this may take a while)...
Checking if previous version installed with pip...

Installing application requirements...

Received error code 1
Failed to install application requirements: exiting.

**Comment by gverduci** [comment]
Installation in a python virtual environment works

https://github.com/damonlynch/rapid-photo-downloader/blob/main/README.md#installation-into-a-python-virtual-environment

**Comment by damonlynch** [comment]
Unfortunately, I need to depreciate the use of the script, because I am unable to maintain it due to my significant hand injury. I can write the code using Dragon NaturallySpeaking and PyCharm for Windows, but actually testing the script in a variety of Linux distributions is a nightmare because it requires a lot of typing.

I have updated the project readme to make a note about the depreciation.
