### ISSUE TITLE
0.9.34: Thumbnail mouseover shows empty yellow fields

### ISSUE THREAD

**Issue by bachrocks** [damonlynch/rapid-photo-downloader#109]
Dear Damian & team

With v0.9.34, the information displayed upon mouseover is just empty fields.
Any idea?
Everything was OK until 0.9.33.
I am on Linux Mint 21.2.

KR,
Martin
![Screenshot from 2023-08-13 14-08-22](https://github.com/damonlynch/rapid-photo-downloader/assets/70584428/4c20ad18-5fc5-4294-a727-df02a2fe01ab)

**Comment by damonlynch** [comment]
Thanks for your bug report. There is no team. I am the only developer.

I assume that you have installed Rapid Photo Downloader from the Linux Mint repository. Is that correct?

If so, the problem you are seeing could be caused by a problem with PyQt5 under Linux Mint 21.2. To check if this is the case, you can install a temporary copy of PyQt5 for your user, direct from the PyQt developer:

`python3 -m pip --user --install --upgrade pyqt5`

If that command complains that pip is not installed, then do this, and then repeat the above command:

`sudo apt install python3-pip`

After you have tested Rapid Photo Downloader with that temporary copy of that PyQt5, if you want to uninstall it run this command:

`python3 -m pip --uninstall pyqt5 pyqt5-sip pyqt5-qt`

**Comment by bachrocks** [comment]
Thank you very much Damon. Rapid Photo Downloader is an impressive one man's work.
I tried to follow your recommendation but "--user" does not work.
My PyQt5 is on 5.15.6. Not the latest-latest version but it is there.
Now I went back to Rapid Photo Downloader 0.9.33 from the repository but it is still the same - empty yellow text fields, no image information visible.
I mean if you have another idea, that's appreciated. Otherwise I don't want to bother you - I'll keep you posted when I found the reason and all the best to your hand.
Cheers,
Martin

**Comment by damonlynch** [comment]
In that case, try the same pip install command without the `--user` directive. It should work.

**Comment by damonlynch** [comment]
I forgot to add, do not use the command `sudo` when running pip commands.

**Comment by bachrocks** [comment]
Many thanks for taking your time Damon.

You were obviously right about the issue with PyQt5.

What eventually worked and resolved the issue:
$ pip3 install --upgrade pyqt5
"Successfully installed PyQt5-Qt5-5.15.2 PyQt5-sip-12.12.2 pyqt5-5.15.9"

Now I have my text fields back.

You're a star :)

Cheers,

Martin
