### ISSUE TITLE
Folders created for images not downloaded

### ISSUE THREAD

**Issue by acebone** [damonlynch/rapid-photo-downloader#229]
Hi

When I use a date in my custom-template folder name, folders are created for all image dates, even for images that are not downloaded.

I use a template like this: "some images I took today <Image date (YYYY-MM-DD)>" and then change the text according to what I shot.

"a walk in the park <Image date (YYYY-MM-DD)>"
"meteor crash in downtown Copenhagen <Image date (YYYY-MM-DD)>"

etc ....

But this will produce a set of empty folders for previous image-dates for images on the camera that has already been downloaded (and therefore aren't downloaded again)

* RPD v. 0.9.36
* Sony ZV-E10
* Ubuntu 23.10

**Comment by damonlynch** [comment]
When you exit the program, are the folders removed?

**Comment by acebone** [comment]
I'm pretty sure that the answer is "no" - I'll let you know with certainty in a couple of days.

However one could argue that even in the preview of the folders to be created (b4 you start the download), folders that aren't necessary shouldn't be displayed - also they shouldn't be created and then exist until the program is exited.

BTW: I find RPD really useful, even with the creation of "ghostfolders", thanks man!

**Comment by damonlynch** [comment]
A bit of context for this conversation: if you want preview folders to exist in the GUI, they must be created on the file system. This is not what I want — it is a limitation of the Qt toolkit. Writing this functionality on top of Qt would take several weeks of work.

If someone wants to volunteer to do their work, that's good. It's not something I want to do myself, because there are much more important priorities.

**Comment by acebone** [comment]
Well I just tested, and the folders are indeed deleted when I exit the program.
