### ISSUE TITLE
Updated sequence numbers not used when changed in user interface between file downloads

### ISSUE THREAD

**Issue by mbaz** [damonlynch/rapid-photo-downloader#55]
Rapid Photo Downloader 0.9.28 on Arch Linux.

I am using RPD to rename photos. An example would be a directory with two raw photos:
```
a --
   |- xx.raw
   |- yy.raw
```
that I want to rename to
```
a --
   |- zz-001.raw
   |- zz-002.raw
```
I set the source and destination directories to `a`, and create a custom preset to rename, using the placeholder "Stored number (Three digits)". In "renaming options", the Stored Number is set to 1:

![image](https://user-images.githubusercontent.com/1630034/151454261-e0470dec-6306-4067-ab73-a8d2b877cb9c.png)

This works fine. Now, I repeat the process in directory `b`, resetting the Stored Number to 1 manually. I also update the custom preset because I want the photos in `b` to have a different prefix.

The problem is that now, images in directory `b` will be numbered starting with "3".

**Comment by damonlynch** [comment]
Please follow the [instructions here](https://damonlynch.net/rapid/documentation/#reportproblem0924) to generate the files I need to be able to see what's going on.

**Comment by damonlynch** [comment]
Thanks.

That's good feedback about needing to zip it. I had no idea. It looks like I need to change the default compression method for the bug report tars.

**Comment by mbaz** [comment]
It seems that github will not even accept `tar.gz` files, which is odd, but a problem since not all Linux distros have `zip` installed by default. However, just changing the filename extension to `txt` seems to be enough to fool the system into accepting the file.

[rpd-bug-report-20220128.txt](https://github.com/damonlynch/rapid-photo-downloader/files/7960205/rpd-bug-report-20220128.txt)

**Comment by damonlynch** [comment]
@mbaz it says [here](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files) that .gz files are supported. That failed in your case?

**Comment by mbaz** [comment]
Oh, that's good to know. `.gz` files were not listed in the list that popped up when it rejected the `tar` file, and that is what I was basing my comment on. Maybe it just listed the most popular file extensions.

**Comment by damonlynch** [comment]
Now I remember I purposely didn't enable compression of the tar after an exception in Rapid Photo Downloader, because I wanted to eliminate any possibility of the compression step being corrupted by a prior problem in the program. However this is very conservative, and given GitHub's requirements it is best to compress it.

**Comment by damonlynch** [comment]
I have identified the [exact line](https://github.com/damonlynch/rapid-photo-downloader/blob/65ffaa9ce91a147e56fe8f2071d384769fcbe7cd/raphodo/renameandmovefile.py#L951) in the code that causes the bug. The sync is overwriting the newer value you entered in the UI instead of updating from it the [newer value like it is supposed to](https://doc.qt.io/qt-5/qsettings.html#sync). It probably is a relatively recent bug in PyQt, sip, or Qt that I need to work around. I am sure I tested it worked circa 2016 when I wrote the code, but I suppose it's also possible I screwed up (strange that it would only be noticed now, however). Assuming it is not a bug in my code from 2016, narrowing down when underlying behavior changed is probably a lot of work! For now I'll see if I can implement a workaround that is not too invasive.

**Comment by damonlynch** [comment]
As it turns out the fix is only one line. That's a relief.

**Comment by damonlynch** [comment]
I forgot to add @mbaz , if you didn't already [take the user survey](https://survey.rapidphotodownloader.com/), please consider doing so.

**Comment by mbaz** [comment]
Thank you for the fix! And I took the survey a few weeks ago.
