### ISSUE TITLE
Autogenerated binary data in raphodo/qrc_resources.py

### ISSUE THREAD

**Issue by scorpi11** [damonlynch/rapid-photo-downloader#73]
Hi,

I'm currently working on a new version of the Debian package. During the review process, Antoine Beaupré (who already worked on the package in the past) found embedded binary blobs in the source code.

This is a serious issue for the Debian package. Embedded copies of other file are not allowed in the Debian policy.

raphodo/qrc_resources.py contains binary encoded resource data. I see that it is autogenerated using pyrcc5 from resources.qrc and the images/ and tips/ folders. However, the release tarball does not contain images/ and tips/.

The current Debian release process fetches the release tarball, verifies the PGP signature and imports the contents from the release tarball.

Would it be an option for you to provide PGP-signed source tarballs for releases that contain the images/ and tips/ folders, so qrc_resources.py can be generated in the build process?

I also found the embedded ZIP file in upgrade.py. I can remove the binary blob automatically when the source is imported into Debian. The automatic update feature is turned off in the Debian packages so the ZIP file is not used.

**Comment by damonlynch** [comment]
Why does the Debian package contain the scripts `install.py` and `upgrade.py`? I don't understand the rules Debian follows when making packages, because I don't package Rapid Photo Downloader for any distro. But I can tell you, those two scripts are totally unnecessary when the program packaged by a distro. They are useful _only_ when installing the program outside of the regular distro packaging system, e.g. apt, dnf etc. Because they will always be included in tarball, in my opinion a distro packager should simply prune them from the distro package.

Second, I personally cannot make those changes you are requesting to the package anytime soon, because I managed to injure my hands while working on the [code for Rapid Photo Downloader earlier this year](https://discuss.pixls.us/t/help-needed-from-folks-who-know-python-to-support-users-due-to-medical-problem/30138). This is a serious injury. I am dictating this text using a voice recognition program running under Windows. 

If you want to make the desired changes to the Python code that generates the source tarball and submit a pull request, please feel free to do so. If you do that, I request that you only add the `images/` and `tips/` files &mdash; do not delete the `raphodo/qrc_resources.py` from the tarball.  

If you cannot make this change, given my very serious injury, and the apparent seriousness of the Debian packaging rules, if you want to simply purge the package from Debian, that's fine with me.

**Comment by scorpi11** [comment]
Hi Damon,

thanks for the quick and detailed reply despite your injury. I second anarcats vote to close the issue. We will find a way to use your git repository and create a source archive that complies with the Debian policy.

Removing the package from Debian is not even an option for me, because I like RPD and use it regularly. :-)

Thanks for you great work and best wishes for your recovery.

**Comment by damonlynch** [comment]
Thanks!
