### ISSUE TITLE
Download stuck at 99 %

### ISSUE THREAD

**Issue by elman22** [damonlynch/rapid-photo-downloader#76]
Hi. Every time I try to download photos, download gets stuck at 99 %. It seem that all pictures has been downloaded - all of them have icon saying "Downloaded as XYZ".

I didn't have the issue before. Currently I use Manjaro Stable, Rapid Photo Downloader is at 0.9.33. I download photos using USB Card Reader, e.g I'm not connecting directly to the camera.

Last lines in the log are:
```
2022-05-23 17:24:36 DEBUG renameandmovefile.py 1000: Finished 198. Getting next task.
2022-05-23 17:24:36 DEBUG rapid.py 3918: Assigning daemon thumbnailer to work on /home/elman/Photos/_import/HGR2022/DSC00639.ARW
2022-05-23 17:24:36 DEBUG rpdsql.py 499: UPDATE files SET downloaded=? WHERE uid=? (True, <uid>)
2022-05-23 17:24:36 DEBUG rapid.py 4238: All files downloaded for disk
2022-05-23 17:24:36 DEBUG rapid.py 4244: Thumbnails generated for disk thus far during download: 0 of 198
```

**Comment by damonlynch** [comment]
Follow the instructions [here](https://damonlynch.net/rapid/documentation/#reportproblem). I have not yet been able to update the documentation to note that recent versions of the program create a compressed tar file, which is necessary for uploading here on GitHub.

**Comment by damonlynch** [comment]
Closing due to no response. Reopen if instructions followed.

**Comment by damonlynch** [comment]
Hi @kozbulski that error message indicates a bug in sip (a program used to generate Python bindings for C++ libraries like PyQt) that was fixed last year by the sip developer. It is not a bug in Rapid Photo Downloader. For some reason, Manjaro is apparently not including the fix made by the sip developer. Therefore, you are seeing the problem. On the Manjaro website somewhere there is a message where I interacted with the Manjaro packagers about this problem. From memory I think that was last year as well. Why the problem is showing up again, after all this time, I'm not sure. As far as I know, this is a problem exclusive to Manjaro. Fedora, Debian etc., do not have this problem.

**Comment by kozbulski** [comment]
Hi Damon,
Thanks for your fast reply.
It's OK for me: your program works, and I know a workaround that does't hurt me much.
Regards,
Uwe

**Comment by elman22** [comment]
Thanks for clarification, guys. I did find Manjaro forum post you were talking about - https://forum.manjaro.org/t/rapid-photo-downloader-not-working-with-pyqt5/102071. It suggests downgrading the package, but I'm fine without thumbnails so I just disable them and everything should work OK. Thank you.
