### ISSUE TITLE
Unable to download from Fuji X10

### ISSUE THREAD

**Issue by jimkp** [damonlynch/rapid-photo-downloader#86]
When I attach the Fuji X10 I see a scanning error saying unable to download from this camera. This has previously worked but not working in 0.9.33.

[rpd-bug-report-20220810.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/9296408/rpd-bug-report-20220810.tar.gz)
.

**Comment by damonlynch** [comment]
Thanks your bug report. Rapid Photo Downloader uses libgphoto2 to access your camera. The Rapid Photo Downloader log file indicates libgphoto2 was not able to access your camera because of an undetermined error. 

To investigate, I suggest installing gphoto2 from your Linux distribution's repositories, and using it from the command line with the verbose option turned on, so you can better determine the error. Another option is to simply remove your camera and plug it in again, as that can sometimes resolve the issue.
