### ISSUE TITLE
Fujifilm X-Pro3: Cannot download

### ISSUE THREAD

**Issue by digital-tinta** [damonlynch/rapid-photo-downloader#97]
[rpd-bug-report-20230103-1.tar.gz](https://github.com/damonlynch/rapid-photo-downloader/files/10340128/rpd-bug-report-20230103-1.tar.gz)

Despite (i) identifying my Fujifilm X-Pro3 and (ii) creating all thumbnails (only one card in the camera), Rapid reports that it cannot download the files. 

Thank you very much.

**Comment by damonlynch** [comment]
Sorry about the long delayed response — I have been dealing with significant health problems. Are you able to test an unreleased version of Rapid Photo downloader that might fix the problem with the exception being generated? It is extremely difficult for me to test because I do not have access to a Fujifilm camera.

As a separate issue, are you saying that only one card in a dual slot camera is only ever detected? Or did you have only one card?

**Comment by digital-tinta** [comment]
Dear Damon, many thanks for replying to my request and above all for your wonderfully useful program! 

My Fujifilm X-Pro3 stopped working, so I can no longer test it. Anyway, I mostly used a card reader to get the job done.

Finally, I hope you are fully recovered from your injury. Best regards.
